version: '3.1'

volumes:
  mysql:
    driver: local

services:
  db:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - '3306:3306'
    volumes:
      - mysql:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint.d/init.sql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8091:8080